version: '2'
services:
  monk-backend:
    container_name: message-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      ELEVEN_LABS_API_KEY: ${ELEVEN_LABS_API_KEY}
